# Generated by Django 6.0.1 on 2026-01-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="characteristics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="display_resolution",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="screen_diagonal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
