# Generated by Django 5.2.10 on 2026-01-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parser_app",
            "0002_product_characteristics_product_display_resolution_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
